const vehicleInit = {
  vehicles: [
    {
      vehicleName: "",
      vin: "",
      license: "",
      vType: "",
      year: "",
      model: "",
      make: "",
      registration: "",
      vImage: "",
      status: "",
      doors: "",
      tank: "",
      cylinders: "",
      vOptions: "",
      odometer: "",
      fType: "",
      eType: "",
      ownership: "",
      color: "",
      bType: "",
      mileage: "",
      transmission: "",
      leaseComp: "",
      leaseAmt: "",
      deposit: "",
      leaseTerm: "",
      leaseExp: "",
      serviceDate: "",
      purchaseDate: "",
      depreciation: "",
      interest: "",
      insuranceAmount: "",
      insuranceComp: "",
      insuranceDuration: "",
      insuranceStartDate: "",
      insuranceExp: "",
      licenseIssueDate: "",
      issuingState: "",
      licenseExpDate: "",
      roadTax: "",
      issuingBody: "",
    },
  ],
};

const customerInit = {
  customers: [
    {
      licenseNo: "",
      customerName: "",
      emergency: "",
      eName: "",
      email: "",
      status: "",
      phone: "",
      licenseIssueDate: "",
      licenseExp: "",
      address: "",
      drivingLicense: "",
      dob: "",
      cImage: "",
      insuranceComp: "",
      policy: "",
      licenseStartDate: "",
      state: "",
      country: "",
    },
  ],
};

export { vehicleInit, customerInit };
